sudo: required
services:
  - docker
env:
  global:
      - SHA=$(git rev-prase HEAD)
      - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install: #You have to do the following steps in order to setup multiple services or components
  - openssl aes-256-cbc -K $encrypted_0c35eebf403c_key -iv $encrypted_0c35eebf403c_iv -in service-account.json.enc -out service-account.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file service account.json
  - gcloud set project multi-k8s-259613
  - gcloud config set compute/zone europe-west3-b
  - gcloud container clusters get-credentials multi-cluster
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t ferastamimi95/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run ferastamimi95/react-test npm test -- --coverage

deploy:
  provider: script
  script: bash ./deploy.sh #a custom command we named deploy.sh that will run our commands
  on:
    branch: master
